### ISSUE TITLE
gulp-util is deprecated -replace it,

### ISSUE THREAD

**Issue by tomchentw** [tomchentw/imagemin-lint-staged#1]
warning imagemin-lint-staged > imagemin-gifsicle > gifsicle > bin-build > download > gulp-decompress > gulp-util@3.0.8: gulp-util is deprecated -replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

**Comment by enwokoma** [comment]
Fixed in gulp 4.

**Comment by enwokoma** [comment]
use npm install gulp@next (or gulp@4) to install Gulp 4.

**Comment by enwokoma** [comment]
That should fix your problem. 
Thank me later! 😂

**Comment by tomchentw** [comment]
Fixed by #4
